name: Steam Idle Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Idle Script
        env:
          ACCOUNT_NAME: ${{ secrets.STEAM_USERNAME }}
          PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          GAMES: ${{ secrets.STEAM_GAMES }}
        run: node index.js
